Repository Framstag/libosmscout, pull requests merged in 2022-10, with the labels that each got.

#1323 Try to fix/analyse mainSlotWidth=0.0
  libosmscout-map/src/osmscoutmap/MapPainter.cpp
Labels: bugfix

#1333 Support scaling contour symbols for iOS/OSX
  libosmscout-map-iosx/src/osmscout/MapPainterIOS.mm
Labels: renderer

#1336 First version of new placement code
  libosmscout-map-qt/src/osmscoutmapqt/MapPainterQt.cpp
  libosmscout-map/include/osmscoutmap/LabelLayouter.h
  libosmscout-map/src/osmscoutmap/LabelLayouter.cpp
  libosmscout-map/src/osmscoutmap/MapParameter.cpp
Labels: feature

#1343 Clean up of Location index generation code
  libosmscout-import/include/osmscoutimport/GenLocationIndex.h
  libosmscout-import/src/osmscoutimport/GenLocationIndex.cpp
Labels: refactoring
