Repository Framstag/libosmscout, pull requests merged in 2022-08, with the labels that each got.

#1284 Qt6 support - Add Core5Compact module to meson build
  meson.build
Labels: refactoring

#1279 setup IMPORTED_LOCATION_<CONFIG> cmake properties
  cmake/libosmscoutConfig.cmake.in
Labels: bugfix

#1286 OpenGL projection
  Demos/src/DrawMapOpenGL.cpp
  libosmscout-map-opengl/CMakeLists.txt
  libosmscout-map-opengl/data/shaders/AreaVertexShader.vert
  libosmscout-map-opengl/data/shaders/GroundVertexShader.vert
  libosmscout-map-opengl/data/shaders/PathVertexShader.vert
  libosmscout-map-opengl/data/shaders/Projection.vert
  libosmscout-map-opengl/data/shaders/QuadVertexShader.vert
  libosmscout-map-opengl/data/shaders/TextVertexShader.vert
  libosmscout-map-opengl/include/meson.build
  libosmscout-map-opengl/include/osmscoutmapopengl/MapPainterOpenGL.h
  libosmscout-map-opengl/include/osmscoutmapopengl/MapProjection.h
  libosmscout-map-opengl/include/osmscoutmapopengl/OpenGLMapData.h
  libosmscout-map-opengl/include/osmscoutmapopengl/OpenGLProjection.h
  libosmscout-map-opengl/src/osmscoutmapopengl/MapPainterOpenGL.cpp
  libosmscout/include/osmscout/util/Projection.h
Labels: renderer, OpenGL, bugfix

#1287 Docker ubuntu 2204
  ci/docker/buildAll.sh
  ci/docker/runAll.sh
  ci/docker/ubuntu_21.10_aarch64_gcc_cmake/arm64.list
  ci/docker/ubuntu_21.10_aarch64_gcc_cmake/build.sh
  ci/docker/ubuntu_21.10_aarch64_gcc_cmake/run.sh
  ci/docker/ubuntu_22.04_aarch64_gcc_cmake/Dockerfile
  ci/docker/ubuntu_22.04_aarch64_gcc_cmake/arm64.list
  ci/docker/ubuntu_22.04_aarch64_gcc_cmake/build.sh
  ci/docker/ubuntu_22.04_aarch64_gcc_cmake/data/build.sh
  ci/docker/ubuntu_22.04_aarch64_gcc_cmake/run.sh
  ci/docker/ubuntu_22.04_gcc_cmake/Dockerfile
  ci/docker/ubuntu_22.04_gcc_cmake/build.sh
  ci/docker/ubuntu_22.04_gcc_cmake/data/build.sh
  ci/docker/ubuntu_22.04_gcc_cmake/run.sh
Labels: refactoring

#1288 drop support of Ubuntu 18.04, GCC 7 did not fully support <filesystem>
  ci/docker/buildAll.sh
  ci/docker/runAll.sh
  ci/docker/ubuntu_18.04_gcc_cmake/Dockerfile
  ci/docker/ubuntu_18.04_gcc_cmake/build.sh
  ci/docker/ubuntu_18.04_gcc_cmake/data/build.sh
  ci/docker/ubuntu_18.04_gcc_cmake/run.sh
Labels: refactoring

#1285 Qt6 support:
  libosmscout-client-qt/include/osmscoutclientqt/InstalledVoicesModel.h
  libosmscout-client-qt/include/osmscoutclientqt/NavigationModule.h
  libosmscout-client-qt/src/osmscoutclientqt/AvailableMapsModel.cpp
  libosmscout-client-qt/src/osmscoutclientqt/DBInstance.cpp
  libosmscout-client-qt/src/osmscoutclientqt/InstalledVoicesModel.cpp
  libosmscout-client-qt/src/osmscoutclientqt/MapManager.cpp
  libosmscout-client-qt/src/osmscoutclientqt/NavigationModule.cpp
  libosmscout-client-qt/src/osmscoutclientqt/OSMScoutQt.cpp
Labels: feature
