Repository Framstag/libosmscout, pull requests merged in 2022-11, with the labels that each got.

#1348 Cleanup of GenLocationIndex code and global GetBoundingBox() methods.
  DumpData/src/DumpData.cpp
  libosmscout-import/include/osmscoutimport/GenLocationIndex.h
  libosmscout-import/src/osmscoutimport/GenLocationIndex.cpp
  libosmscout-import/src/osmscoutimport/SortNodeDat.cpp
  libosmscout-map-opengl/src/osmscoutmapopengl/MapPainterOpenGL.cpp
  libosmscout/include/osmscout/Area.h
  libosmscout/include/osmscout/Way.h
  libosmscout/include/osmscout/util/Geometry.h
  libosmscout/src/osmscout/Area.cpp
  libosmscout/src/osmscout/LocationDescriptionService.cpp
  libosmscout/src/osmscout/util/PolygonCenter.cpp
Labels: refactoring

#1350 fix placement of contour symbols for short ways
  libosmscout-map-qt/src/osmscoutmapqt/MapPainterQt.cpp
  libosmscout-map/src/osmscoutmap/MapPainter.cpp
  libosmscout/include/osmscout/util/Transformation.h
Labels: renderer, bugfix

#1349 transliterate support for text index (marisa-based search)
  Demos/src/LookupText.cpp
  Import/src/Import.cpp
  Tests/CMakeLists.txt
  Tests/data/testregion/areaarea.idx
  Tests/data/testregion/areanode.idx
  Tests/data/testregion/arearoute.idx
  Tests/data/testregion/areas.dat
  Tests/data/testregion/areasopt.dat
  Tests/data/testregion/areaway.idx
  Tests/data/testregion/intersections.dat
  Tests/data/testregion/intersections.idx
  Tests/data/testregion/location.idx
  Tests/data/testregion/nodes.dat
  Tests/data/testregion/route.dat
  Tests/data/testregion/router.dat
  Tests/data/testregion/router2.dat
  Tests/data/testregion/textloc.dat
  Tests/data/testregion/textother.dat
  Tests/data/testregion/textpoi.dat
  Tests/data/testregion/textregion.dat
  Tests/data/testregion/types.dat
  Tests/data/testregion/ways.dat
  Tests/data/testregion/waysopt.dat
  Tests/meson.build
  Tests/src/TextLookupTest.cpp
  libosmscout-client-qt/src/osmscoutclientqt/SearchModule.cpp
  libosmscout-import/include/osmscoutimport/GenTextIndex.h
  libosmscout-import/include/osmscoutimport/ImportParameter.h
  libosmscout-import/src/osmscoutimport/GenTextIndex.cpp
  libosmscout-import/src/osmscoutimport/ImportParameter.cpp
  libosmscout/include/osmscout/TextSearchIndex.h
  libosmscout/src/osmscout/TextSearchIndex.cpp
Labels: feature, importer, search-marisa
