Repository Framstag/libosmscout, pull requests merged in 2022-09, with the labels that each got.

#1299 Use of vcpkg.json files for defining vcpkg packages to use
  .github/workflows/build_and test_on_vs2019.yml
  vcpkg_full.json
  vcpkg_medium.json
  vcpkg_minimum.json
Labels: maintenance

#1300 Qt6 support: Add a minimal Qt6 based build
  .github/workflows/build_and test_on_ubuntu_22_04.yml
  Tests/meson.build
  ci/docker/buildAll.sh
  ci/docker/runAll.sh
  ci/docker/ubuntu_22.04_gcc_meson_qt6/Dockerfile
  ci/docker/ubuntu_22.04_gcc_meson_qt6/build.sh
  ci/docker/ubuntu_22.04_gcc_meson_qt6/data/build.sh
  ci/docker/ubuntu_22.04_gcc_meson_qt6/run.sh
Labels: maintenance

#1302 Some general code cleanup
  Tests/src/PerformanceTest.cpp
  libosmscout-client-qt/src/osmscoutclientqt/DBInstance.cpp
  libosmscout-client-qt/src/osmscoutclientqt/DBThread.cpp
  libosmscout-map/include/osmscoutmap/StyleConfig.h
  libosmscout-map/parser/OSS/OSS.atg
  libosmscout-map/src/osmscoutmap/StyleConfig.cpp
  libosmscout-map/src/osmscoutmap/oss/Parser.cpp
  libosmscout/src/osmscout/util/File.cpp
Labels: maintenance

#1303 Introduce the ContourSymbolData struct to simply API arguments
  libosmscout-client-qt/src/osmscoutclientqt/MapRenderer.cpp
  libosmscout-map-agg/include/osmscoutmapagg/MapPainterAgg.h
  libosmscout-map-agg/src/osmscoutmapagg/MapPainterAgg.cpp
  libosmscout-map-cairo/include/osmscoutmapcairo/MapPainterCairo.h
  libosmscout-map-cairo/src/osmscoutmapcairo/MapPainterCairo.cpp
  libosmscout-map-directx/include/osmscoutmapdirectx/MapPainterDirectX.h
  libosmscout-map-directx/src/osmscoutmapdirectx/MapPainterDirectX.cpp
  libosmscout-map-gdi/include/osmscoutmapgdi/MapPainterGDI.h
  libosmscout-map-gdi/src/osmscoutmapgdi/MapPainterGDI.cpp
  libosmscout-map-iosx/include/osmscoutmapiosx/MapPainterIOS.h
  libosmscout-map-iosx/src/osmscout/MapPainterIOS.mm
  libosmscout-map-qt/include/osmscoutmapqt/MapPainterQt.h
  libosmscout-map-qt/src/osmscoutmapqt/MapPainterQt.cpp
  libosmscout-map-svg/include/osmscoutmapsvg/MapPainterSVG.h
  libosmscout-map-svg/src/osmscoutmapsvg/MapPainterSVG.cpp
  libosmscout-map/include/osmscoutmap/MapPainter.h
  libosmscout-map/include/osmscoutmap/MapPainterNoOp.h
  libosmscout-map/src/osmscoutmap/MapPainter.cpp
  libosmscout-map/src/osmscoutmap/MapPainterNoOp.cpp
Labels: maintenance

#1304 Better contour label positioning
  libosmscout-map/include/osmscoutmap/LabelLayouter.h
  libosmscout-map/src/osmscoutmap/MapPainter.cpp
Labels: feature

#1305 Fix just introduced bug in symbol positioning in cairo
  libosmscout-map-cairo/src/osmscoutmapcairo/MapPainterCairo.cpp
Labels: bugfix

#1306 Added icons for
  libosmscout/data/icons/14x14/standard/fast_food.png
  libosmscout/data/icons/14x14/standard/restaurant.png
  libosmscout/data/icons/svg/standard/fast_food.svg
  libosmscout/data/icons/svg/standard/restaurant.svg
  stylesheets/include/man_made.oss
Labels: feature

#1307 Improved DrawPath signature
  libosmscout-map-agg/include/osmscoutmapagg/MapPainterAgg.h
  libosmscout-map-agg/src/osmscoutmapagg/MapPainterAgg.cpp
  libosmscout-map-cairo/include/osmscoutmapcairo/MapPainterCairo.h
  libosmscout-map-cairo/src/osmscoutmapcairo/MapPainterCairo.cpp
  libosmscout-map-directx/include/osmscoutmapdirectx/MapPainterDirectX.h
  libosmscout-map-directx/src/osmscoutmapdirectx/MapPainterDirectX.cpp
  libosmscout-map-gdi/include/osmscoutmapgdi/MapPainterGDI.h
  libosmscout-map-gdi/src/osmscoutmapgdi/MapPainterGDI.cpp
  libosmscout-map-iosx/include/osmscoutmapiosx/MapPainterIOS.h
  libosmscout-map-iosx/src/osmscout/MapPainterIOS.mm
  libosmscout-map-qt/include/osmscoutmapqt/MapPainterQt.h
  libosmscout-map-qt/src/osmscoutmapqt/MapPainterQt.cpp
  libosmscout-map-svg/include/osmscoutmapsvg/MapPainterSVG.h
  libosmscout-map-svg/src/osmscoutmapsvg/MapPainterSVG.cpp
  libosmscout-map/include/osmscoutmap/MapPainter.h
  libosmscout-map/include/osmscoutmap/MapPainterNoOp.h
  libosmscout-map/src/osmscoutmap/MapPainter.cpp
  libosmscout-map/src/osmscoutmap/MapPainterNoOp.cpp
  libosmscout/include/osmscout/util/Transformation.h
Labels: maintenance

#1308 Improved CoordBufferRange
  Tests/src/CoordBufferTest.cpp
  libosmscout-map-cairo/src/osmscoutmapcairo/MapPainterCairo.cpp
  libosmscout-map-qt/src/osmscoutmapqt/MapPainterQt.cpp
  libosmscout-map/src/osmscoutmap/MapPainter.cpp
  libosmscout/include/osmscout/util/Transformation.h
  libosmscout/src/osmscout/util/Transformation.cpp
Labels: maintenance

#1309 Introduced ScreenBox, a bounding box for (near) screen rectangular areas
  Tests/src/MultiDBRouting.cpp
  libosmscout-map/include/osmscoutmap/Styles.h
  libosmscout-map/src/osmscoutmap/Styles.cpp
  libosmscout/CMakeLists.txt
  libosmscout/include/meson.build
  libosmscout/include/osmscout/Pixel.h
  libosmscout/include/osmscout/util/ScreenBox.h
  libosmscout/src/meson.build
  libosmscout/src/osmscout/util/ScreenBox.cpp
Labels: refactoring

#1311 Scalable contour symbols
  libosmscout-map-agg/include/osmscoutmapagg/MapPainterAgg.h
  libosmscout-map-agg/src/osmscoutmapagg/MapPainterAgg.cpp
  libosmscout-map-cairo/include/osmscoutmapcairo/MapPainterCairo.h
  libosmscout-map-cairo/src/osmscoutmapcairo/MapPainterCairo.cpp
  libosmscout-map-directx/include/osmscoutmapdirectx/MapPainterDirectX.h
  libosmscout-map-directx/src/osmscoutmapdirectx/MapPainterDirectX.cpp
  libosmscout-map-gdi/include/osmscoutmapgdi/MapPainterGDI.h
  libosmscout-map-gdi/src/osmscoutmapgdi/MapPainterGDI.cpp
  libosmscout-map-iosx/include/osmscoutmapiosx/MapPainterIOS.h
  libosmscout-map-iosx/src/osmscout/MapPainterIOS.mm
  libosmscout-map-qt/include/osmscoutmapqt/MapPainterQt.h
  libosmscout-map-qt/src/osmscoutmapqt/MapPainterQt.cpp
  libosmscout-map-svg/include/osmscoutmapsvg/MapPainterSVG.h
  libosmscout-map-svg/src/osmscoutmapsvg/MapPainterSVG.cpp
  libosmscout-map/include/osmscoutmap/LabelLayouter.h
  libosmscout-map/include/osmscoutmap/MapPainter.h
  libosmscout-map/include/osmscoutmap/MapPainterNoOp.h
  libosmscout-map/include/osmscoutmap/Styles.h
  libosmscout-map/include/osmscoutmap/SymbolRenderer.h
  libosmscout-map/src/osmscoutmap/MapPainter.cpp
  libosmscout-map/src/osmscoutmap/MapPainterNoOp.cpp
  libosmscout-map/src/osmscoutmap/Styles.cpp
  libosmscout-map/src/osmscoutmap/SymbolRenderer.cpp
  stylesheets/include/roads.oss
  webpage/content/documentation/stylesheet.md
Labels: feature

#1315 Fix VS2019 build
  libosmscout/include/osmscout/Pixel.h
Labels: bugfix

#1316 Fix compiler warning
  libosmscout-import/src/osmscoutimport/Import.cpp
Labels: bugfix

#1328 scale symbol space together with contour symbols
  libosmscout-map/src/osmscoutmap/MapPainter.cpp
Labels: renderer

#1329 Symbol placement
  libosmscout-map/src/osmscoutmap/SymbolRenderer.cpp
  libosmscout/include/osmscout/Pixel.h
  libosmscout/src/osmscout/Pixel.cpp
Labels: bugfix

#1324 Try to fix the contour label visibility problem as described in issue…
  libosmscout-map/include/osmscoutmap/LabelLayouter.h
  libosmscout-map/src/osmscoutmap/MapPainter.cpp
  libosmscout-map/src/osmscoutmap/MapParameter.cpp
Labels: bugfix

#1332 Fix iOS icons scaling on retina screens
  libosmscout-map-iosx/src/osmscout/MapPainterIOS.mm
Labels: renderer, bugfix
