Repository Framstag/libosmscout, pull requests merged in 2023-03, with the labels that each got.

#1386 improve GeoCoord string parsing
  Tests/src/GeoCoordParse.cpp
  libosmscout/include/osmscout/GeoCoord.h
  libosmscout/src/osmscout/GeoCoord.cpp
  libosmscout/src/osmscout/OptimizeWaysLowZoom.cpp
  libosmscout/src/osmscout/WaterIndex.cpp
  libosmscout/src/osmscout/util/CmdLineParsing.cpp
Labels: feature

#1389 Increase minimum meson version to 0.63
  meson.build
Labels: maintenance

#1392 FIx sonar warnings regarding use of identifier reserved by C++ itself.
  Demos/src/PositionSimulator.cpp
  libosmscout-client-qt/include/osmscoutclientqt/InputHandler.h
  libosmscout-client-qt/include/osmscoutclientqt/RouteDescriptionBuilder.h
  libosmscout-client-qt/include/osmscoutclientqt/RouteStep.h
  libosmscout-client-qt/src/osmscoutclientqt/InputHandler.cpp
  libosmscout-client-qt/src/osmscoutclientqt/RouteDescriptionBuilder.cpp
  libosmscout-client-qt/src/osmscoutclientqt/RouteStep.cpp
  libosmscout-gpx/include/osmscoutgpx/GpxFile.h
  libosmscout-gpx/include/osmscoutgpx/TrackPoint.h
  libosmscout-gpx/include/osmscoutgpx/Waypoint.h
  libosmscout-gpx/src/osmscoutgpx/Export.cpp
  libosmscout-gpx/src/osmscoutgpx/Import.cpp
Labels: bugfix

#1393 Separate project version from library version
  libosmscout-client-qt/meson.build
  libosmscout-gpx/meson.build
  libosmscout-import/meson.build
  libosmscout-map-agg/meson.build
  libosmscout-map-cairo/meson.build
  libosmscout-map-directx/meson.build
  libosmscout-map-gdi/meson.build
  libosmscout-map-iosx/meson.build
  libosmscout-map-opengl/meson.build
  libosmscout-map-qt/meson.build
  libosmscout-map-svg/meson.build
  libosmscout-map/meson.build
  libosmscout-test/meson.build
  libosmscout/meson.build
  meson.build
Labels: build, maintenance

#1394 fix assertion in DrawWayDecoration when way width is zero
  libosmscout-map/src/osmscoutmap/MapPainter.cpp
Labels: bugfix

#1395 fix infinite loop on roundabout node postprocessing
  libosmscout/include/osmscout/routing/RoutePostprocessor.h
  libosmscout/src/osmscout/routing/RoutePostprocessor.cpp
Labels: bugfix

#1396 add extra method with better name instead of default argument
  libosmscout/include/osmscout/routing/RoutePostprocessor.h
  libosmscout/src/osmscout/routing/RoutePostprocessor.cpp
Labels: maintenance
