Repository Framstag/libosmscout, pull requests merged in 2023-04, with the labels that each got.

#1403 lane turn utility
  DumpData/src/DumpData.cpp
  libosmscout-client-qt/include/osmscoutclientqt/NavigationModel.h
  libosmscout-map/include/osmscoutmap/Styles.h
  libosmscout-map/src/osmscoutmap/MapPainter.cpp
  libosmscout-map/src/osmscoutmap/Styles.cpp
  libosmscout/CMakeLists.txt
  libosmscout/include/meson.build
  libosmscout/include/osmscout/TypeFeatures.h
  libosmscout/include/osmscout/navigation/LaneAgent.h
  libosmscout/include/osmscout/routing/RouteDescription.h
  libosmscout/include/osmscout/util/LaneTurn.h
  libosmscout/src/meson.build
  libosmscout/src/osmscout/TypeFeatures.cpp
  libosmscout/src/osmscout/routing/RouteDescription.cpp
  libosmscout/src/osmscout/routing/RoutePostprocessor.cpp
  libosmscout/src/osmscout/util/LaneTurn.cpp
Labels: feature

#1401 allow negative elevation value
  Tests/data/testregion/areaarea.idx
  Tests/data/testregion/areanode.idx
  Tests/data/testregion/areas.dat
  Tests/data/testregion/areaway.idx
  Tests/data/testregion/bounding.dat
  Tests/data/testregion/coverage.idx
  Tests/data/testregion/intersections.dat
  Tests/data/testregion/intersections.idx
  Tests/data/testregion/location.idx
  Tests/data/testregion/nodes.dat
  Tests/data/testregion/route.dat
  Tests/data/testregion/router.dat
  Tests/data/testregion/router2.dat
  Tests/data/testregion/textloc.dat
  Tests/data/testregion/textother.dat
  Tests/data/testregion/textpoi.dat
  Tests/data/testregion/textregion.dat
  Tests/data/testregion/types.dat
  Tests/data/testregion/water.idx
  Tests/data/testregion/ways.dat
  Tests/data/testregion/waysopt.dat
  libosmscout/include/osmscout/TypeConfig.h
  libosmscout/include/osmscout/TypeFeatures.h
  libosmscout/src/osmscout/TypeFeatures.cpp
Labels: feature

#1404 fix crash when stylesheet loading fails
  libosmscout-client-qt/src/osmscoutclientqt/MapRenderer.cpp
Labels: bug

#1412 Issue #1045 - Cleanup of MapPainter
  .clang-tidy
  Demos/src/RoutingAnimation.cpp
  Tests/CMakeLists.txt
  Tests/data/testregion/areaarea.idx
  Tests/data/testregion/areanode.idx
  Tests/data/testregion/areas.dat
  Tests/data/testregion/location.idx
  Tests/data/testregion/nodes.dat
  Tests/data/testregion/textother.dat
  Tests/data/testregion/textpoi.dat
  Tests/data/testregion/textregion.dat
  Tests/data/testregion/types.dat
  Tests/meson.build
  Tests/src/ScreenBox.cpp
  libosmscout-client-qt/src/osmscoutclientqt/IconAnimation.cpp
  libosmscout-client-qt/src/osmscoutclientqt/IconLookup.cpp
  libosmscout-client-qt/src/osmscoutclientqt/InputHandler.cpp
  libosmscout-client-qt/src/osmscoutclientqt/LookupModule.cpp
  libosmscout-client-qt/src/osmscoutclientqt/MapRenderer.cpp
  libosmscout-client-qt/src/osmscoutclientqt/MapWidget.cpp
  libosmscout-client-qt/src/osmscoutclientqt/PlaneMapRenderer.cpp
  libosmscout-client-qt/src/osmscoutclientqt/TiledRenderingHelper.cpp
  libosmscout-map-agg/include/osmscoutmapagg/MapPainterAgg.h
  libosmscout-map-agg/src/osmscoutmapagg/MapPainterAgg.cpp
  libosmscout-map-cairo/include/osmscoutmapcairo/MapPainterCairo.h
  libosmscout-map-cairo/src/osmscoutmapcairo/MapPainterCairo.cpp
  libosmscout-map-directx/include/osmscoutmapdirectx/MapPainterDirectX.h
  libosmscout-map-directx/src/osmscoutmapdirectx/MapPainterDirectX.cpp
  libosmscout-map-gdi/include/osmscoutmapgdi/MapPainterGDI.h
  libosmscout-map-gdi/src/osmscoutmapgdi/MapPainterGDI.cpp
  libosmscout-map-iosx/include/osmscoutmapiosx/MapPainterIOS.h
  libosmscout-map-iosx/src/osmscout/MapPainterIOS.mm
  libosmscout-map-opengl/src/osmscoutmapopengl/MapPainterOpenGL.cpp
  libosmscout-map-qt/include/osmscoutmapqt/MapPainterQt.h
  libosmscout-map-qt/src/osmscoutmapqt/MapPainterQt.cpp
  libosmscout-map-svg/include/osmscoutmapsvg/MapPainterSVG.h
  libosmscout-map-svg/src/osmscoutmapsvg/MapPainterSVG.cpp
  libosmscout-map/CMakeLists.txt
  libosmscout-map/include/meson.build
  libosmscout-map/include/osmscoutmap/BatchMapPainter.h
  libosmscout-map/include/osmscoutmap/LabelLayouter.h
  libosmscout-map/include/osmscoutmap/MapPainter.h
  libosmscout-map/include/osmscoutmap/MapPainterNoOp.h
  libosmscout-map/include/osmscoutmap/MapPainterStatistics.h
  libosmscout-map/src/meson.build
  libosmscout-map/src/osmscoutmap/MapPainter.cpp
  libosmscout-map/src/osmscoutmap/MapPainterNoOp.cpp
  libosmscout-map/src/osmscoutmap/MapPainterStatistics.cpp
  libosmscout/include/osmscout/Pixel.h
  libosmscout/include/osmscout/Way.h
  libosmscout/include/osmscout/util/Projection.h
  libosmscout/include/osmscout/util/ScreenBox.h
  libosmscout/src/osmscout/Pixel.cpp
  libosmscout/src/osmscout/util/Projection.cpp
  libosmscout/src/osmscout/util/ScreenBox.cpp
Labels: refactoring, maintenance

#1413 Issue #1045 - Cleanup of MapPainter
  Demos/include/DrawMap.h
  Demos/src/Tiler.cpp
  OSMScoutOpenGL/src/OSMScoutOpenGL.cpp
  Tests/src/CoordBufferTest.cpp
  Tests/src/DrawTextQt.cpp
  Tests/src/LabelPathTest.cpp
  Tests/src/PerformanceTest.cpp
  libosmscout-client-qt/src/osmscoutclientqt/DBJob.cpp
  libosmscout-client-qt/src/osmscoutclientqt/MapRenderer.cpp
  libosmscout-client-qt/src/osmscoutclientqt/PlaneMapRenderer.cpp
  libosmscout-client-qt/src/osmscoutclientqt/TiledMapRenderer.cpp
  libosmscout-client-qt/src/osmscoutclientqt/TiledRenderingHelper.cpp
  libosmscout-map-agg/src/osmscoutmapagg/MapPainterAgg.cpp
  libosmscout-map-cairo/src/osmscoutmapcairo/MapPainterCairo.cpp
  libosmscout-map-opengl/src/osmscoutmapopengl/MapPainterOpenGL.cpp
  libosmscout-map-qt/src/osmscoutmapqt/MapPainterQt.cpp
  libosmscout-map-svg/src/osmscoutmapsvg/MapPainterSVG.cpp
  libosmscout-map/include/osmscoutmap/LabelLayouter.h
  libosmscout-map/include/osmscoutmap/LabelPath.h
  libosmscout-map/include/osmscoutmap/MapPainter.h
  libosmscout-map/src/osmscoutmap/LabelPath.cpp
  libosmscout-map/src/osmscoutmap/MapPainter.cpp
  libosmscout-map/src/osmscoutmap/MapService.cpp
  libosmscout/include/osmscout/Pixel.h
  libosmscout/include/osmscout/util/Projection.h
  libosmscout/include/osmscout/util/ScreenBox.h
  libosmscout/include/osmscout/util/Transformation.h
  libosmscout/src/osmscout/util/ScreenBox.cpp
  libosmscout/src/osmscout/util/Transformation.cpp
Labels: refactoring, maintenance

#1414 Try fixing vcpkg based build
  .github/workflows/build_and test_on_vs2019.yml
  libosmscout/include/osmscout/util/Projection.h
Labels: build, maintenance

#1419 Fix unity build
  libosmscout/src/osmscout/projection/MercatorProjection.cpp
Labels: bug

#1420 add utility for trim string
  Tests/src/StringUtils.cpp
  libosmscout/include/osmscout/util/String.h
  libosmscout/src/osmscout/TypeFeatures.cpp
  libosmscout/src/osmscout/util/String.cpp
Labels: feature
